---
name: deploy
on:
  push:
    branches:
      - main


jobs:
  terrafor-format:
    name: Terraform-format
    runs-on: ubuntu-latest

    steps:
      - name: Chechout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.5"
      - name: terraform format
        run: terraform fmt -check -diff